### ISSUE TITLE
More tools on try.elv.sh

### ISSUE THREAD

**Issue by notramo** [elves/try#1]
Sometimes I want to show the efficiency of the Linux CLI environment to someone, or teach some Linux stuff while they are on a Windows machine. The web interface is suitable for these cases.
It would be cool if some of the greatest Linux command line tools would be available on [try.elv.sh](https://try.elv.sh).
[`exa`](https://the.exa.website/) - a modern and more powerful replacement for `ls`
[`fd`](https://github.com/sharkdp/fd) - a modern replacement for `find`
[Kakoune](http://kakoune.org) - a powerful code editor
[`ripgrep`](https://github.com/BurntSushi/ripgrep) - a modern and fast replacement for `grep`
[Pijul](https://pijul.com/) - a modern and lightweight version tracking system

**Comment by xiaq** [comment]
try.elv.sh is based on the Dockerfile in this repo. I am open to pull requests to add more tools.

AFAICT none of those tools are packaged in Alpine, so it will require some building steps.

Also, I think we should keep the base image as is and add another Dockerfile for building the "goodies" version; to do that, you should create a new directory in the repo and add a `Dockerfile` to it.

**Comment by notramo** [comment]
@xiaq I'm not familiar with Docker. (But I want to learn it.)
Kakoune is available in the Alpine repos. Could you add it? (Or should it also go to the goodies version?)
Other tools needs custom build or getting prebuilt binaries from their upstream releases (most of them are static). I will add them after I learn Docker.

**Comment by xiaq** [comment]
@notramo Kakoune has been packaged in edge but not in the stable release we use (3.8).

I would say that things that can be installed from the repo directly can go into the base version while things that require compilation goes into the goodies version.

**Comment by xiaq** [comment]
I've added everything mentioned in the original request, except that I added eza instead of exa because only the former is packaged in Alpine and apparently the latter is now [unmaintained](https://github.com/ogham/exa/issues/1243).

**Comment by xiaq** [comment]
Since waiting for Alpine to package stuff has turned out to be a winning strategy, I think I'm going to be more conservative here and say that I'll just to stick to software that's available in Alpine's repos, so I'll close this.

You can fork this repo and set up your own instance BTW, this new Docker thing makes it super easy :)
