### ISSUE TITLE
Predefined workspaces

### ISSUE THREAD

**Issue by notramo** [elves/try#2]
Predefined workspaces could be user directories that contain files, custom `rc.elv`, and so. It could be available as e.g. https://try.elv.sh/?arg=workspace:https://{git_repo_url}
Use cases:
- Show the usability of custom shell/cli tools config. The default install is not so powerful.
- I am writing a CLI tutorial, and it would be great to include the try.elv.sh page embedded in the tutorial. It would be even more powerful to have files created for demonstration purposes, because example commands are much easier to understand via real examples.

The `--permit-arguments` option of `gotty` could be used to clone a git repo from e.g. GitLab to the home directory. The repo could contain an `rc.elv` file, and other config files.

**Comment by xiaq** [comment]
I settled for a simpler solution - you can pass anything in the arg and it gets written to a `setup` script.

It'd be better if this gets automatically executed too, but I'm a bit terrified of doing anything more complex in bash, especially when it could easily lead to privilege escalation.
